### ISSUE TITLE
Problems about masking details. 

### ISSUE THREAD

**Issue by OuYanXi** [LividWo/Perturbed-Masking#8]
when calculating the impact of x_i+1 to x_i,  is there  a must to mask x_i?  I have done a test  on sentence segment without masking x_i ,  and it achieved a comparatively better result with less matrix calculation.

**Comment by LividWo** [comment]
I remember that we also tried the setting in which we do not mask x_i, and it performs poorly on syntactic tasks.
We suspect the reason is that if you do not mask x_i, x_i+1 will only have a very small impact on x_i's representation, and make parsing difficult (since the impact values are quite close to each other).
But yeh, it's also possible only masking once can also do well on sentence segmentation task. 
Would be great if you would like to share some of your results, e.g., performance of masking x_i and x_i+1 vs masking x_i+1
